### ISSUE TITLE
where is the model.pth?

### ISSUE THREAD

**Issue by Owen718** [mkartik/Shallow-UWnet#4]
Hi! Your work is very impressive! I want to test some underwater images used your implementation. Could you provide the model.pth file, please?

**Comment by Wubl-cy** [comment]
Hi!Have you achieved the results in the paper? Can you share your experience?THANK YOU!

**Comment by Owen718** [comment]
> Hi!Have you achieved the results in the paper? Can you share your experience?THANK YOU!

Hi! I am trying to design a SOTA NN model. I haven't tried training shallow-UWnet.But I had tested the FUniE-GAN on the EUVP-dark dataset. I think the water-net indicator on UIEB and the shallow-UWnet indicator on EUVP-dark given in the paper using different indicator test codes. If you have any questions, you can talk with me!

**Comment by Wubl-cy** [comment]
Thank you for your help. Due to the needs of the project, I would like to test the code related to underwater image enhancement. Do you have any other recommendations? If so, you are welcome to email me at ***@***.***



At 2021-04-28 09:52:05, "Mr.Ye" ***@***.***> wrote:

Hi!Have you achieved the results in the paper? Can you share your experience?THANK YOU!

Hi! I am trying to design a SOTA NN model. I haven't tried training shallow-UWnet.But I had tested the FUniE-GAN on the EUVP-dark dataset. I think the water-net indicator on UIEB and the shallow-UWnet indicator on EUVP-dark given in the paper using different indicator test codes. If you have any questions, you can talk with me!

**Comment by mkartik** [comment]
Hi @Owen718 and @wubilang, thank you, and sorry for my delay in response. I have now uploaded the model.ckpt (link in the README.md) which can be used to test the underwater images I have used in my implementation.
